try {
    throw "TypeError"
}
catch {
    func(e) {
	return assert(e === "TypeError", "try-catch")
    }
}
